version: '3.7'

services:
  yamdb_prod:
    image: kzorikov/yamdb_final:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/home/yamdb/api_yamdb/static/
      - media_value:/home/yamdb/api_yamdb/media/
    env_file:
      - ./env/.env.prod
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.db
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/home/yamdb/api_yamdb/static/
      - media_value:/home/yamdb/api_yamdb/media/
    ports:
      - 80:80
    depends_on:
      - yamdb_prod

volumes:
  postgres_data:
  static_value:
  media_value: