# Generated by Django 3.0.5 on 2021-05-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210503_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Название произведения', max_length=100, verbose_name='Название'),
        ),
    ]
